version: '3'
services:
    database:
        image: mariadb:10.6.14
        ports:
            - "${LOCAL_SERVER_IP}:${LOCAL_DB_PORT}:3306"
        restart: on-failure:5
        container_name: "${PRODUCTION_NAME}_db"
        volumes:
            - db_data:/var/lib/mysql
            - ./data/mysql:/docker-entrypoint-initdb.d
        command: [
            '--default_authentication_plugin=mysql_native_password',
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
        ]
        environment:
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_DATABASE: "${MYSQL_NAME}"
            MYSQL_PASSWORD: "${MYSQL_PASS}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASS}"
    wordpress:
        depends_on:
            - database
        image: wordpress:latest
        container_name: "${PRODUCTION_NAME}_wp"
        ports:
            - "${LOCAL_SERVER_IP}:${LOCAL_SERVER_PORT}:80"
        restart: on-failure:5
        volumes:
            - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
            - ./app:/var/www/html
        environment:
            WORDPRESS_DB_HOST: database:${LOCAL_DB_PORT}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASS}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_NAME: ${MYSQL_NAME}
    cli:
        tty: true
        image: wordpress:cli
        container_name: "${PRODUCTION_NAME}_cli"
        user: xfs
        depends_on:
          - wordpress
          - database
        command: >
          /bin/sh -c '
          sleep 10;
          wp core install --path="/var/www/html" --url="http://localhost:${LOCAL_SERVER_PORT}" --title="Local Wordpress By Docker" --admin_user=${ADMIN_USER} --admin_password=${ADMIN_PASS} --admin_email=${ADMIN_EMAIL};
          wp language core install ja --activate --allow-root;
          wp option update timezone_string "Asia/Tokyo" --allow-root;
          '
        volumes:
          - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
          - ./app:/var/www/html
        environment:
            WORDPRESS_DB_HOST: database:${LOCAL_DB_PORT}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASS}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_NAME: ${MYSQL_NAME}
    wordmove:
        tty: true
        depends_on:
            - wordpress
        image: welaika/wordmove
        restart: on-failure:5
        container_name: "${PRODUCTION_NAME}_wordmove"
        command: /bin/bash -c 'apt-get update && apt-get install sshpass && /bin/bash'
        volumes:
            - ./config:/home/
            - ./app:/var/www/html
            - ~/.ssh:/home/.ssh
        environment:
            RUBYOPT: -EUTF-8
            LOCAL_SERVER_PORT: "${LOCAL_SERVER_PORT}"
            LOCAL_DB_NAME: "${MYSQL_NAME}"
            LOCAL_DB_ROOT_PASS: "${MYSQL_ROOT_PASS}"
            PRODUCTION_URL: "${PRODUCTION_URL}"
            PRODUCTION_DIR_PATH: "${PRODUCTION_DIR_PATH}"
            PRODUCTION_DB_NAME: "${PRODUCTION_DB_NAME}"
            PRODUCTION_DB_USER: "${PRODUCTION_DB_USER}"
            PRODUCTION_DB_PASSWORD: "${PRODUCTION_DB_PASSWORD}"
            PRODUCTION_DB_HOST: "${PRODUCTION_DB_HOST}"
            PRODUCTION_DB_PORT: "${PRODUCTION_DB_PORT}"
            PRODUCTION_SSH_HOST: "${PRODUCTION_SSH_HOST}"
            PRODUCTION_SSH_USER: "${PRODUCTION_SSH_USER}"
            PRODUCTION_SSH_PORT: "${PRODUCTION_SSH_PORT}"
volumes:
  db_data:
